
-- FIND OUT THE DEPARTMENT_NAME
-- AND THE MANAGER FIRST_NAME FOR EACH DEPARTMENTS
-- ACCORDING TO THE DEPARTMENT TABLE MANAGER COLUMN COMMENT
--- MANAGER_ID IS FOREIGN KEY TO EMPLOYEE_ID OF EMPLOYEE COLUMN
--- IN A NUTSHELL, THAT IS THE RELATIONSHIP WE ARE GOING TO USE
--- EMPLOYEES.EMPLOYEE_ID = DEPARTMENTS.MANAGER_ID
-- NOTE THAT COLUMN NAMES DOES NOT HAVE TO MATCH AS LONG AS RELATIONSHIP IS DEFINED

SELECT D.DEPARTMENT_NAME, E.FIRST_NAME
FROM DEPARTMENTS D
INNER JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
;

----  CONTINUE FROM ABOVE QUERY, FIND OUT THE MANAGER FIRST_NAME OF Executive

SELECT D.DEPARTMENT_NAME, E.FIRST_NAME
FROM DEPARTMENTS D
INNER JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
WHERE D.DEPARTMENT_NAME = 'Executive'
;

-- FIND OUT THE DEPARTMENT_NAME
--  AND THE MANAGER FIRST_NAME FOR EACH DEPARTMENTS
----  ONLY DISPLAY IF DEPARTMENT_NAME START WITH A

SELECT D.DEPARTMENT_NAME, E.FIRST_NAME
FROM DEPARTMENTS D
INNER JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
WHERE D.DEPARTMENT_NAME LIKE 'A%'
;

--- FIND OUT HOW MANY TOTAL COUNTRIES ARE IN EACH REGION ID
SELECT REGION_ID, COUNT(*) AS "COUNTRY_EACH_REGION"
FROM COUNTRIES
GROUP BY REGION_ID
;

--- FIND OUT HOW MANY COUNTRY IN EACH REGION
--- DISPLAY REGION_NAME AND COUNTRY_COUNT
--- START BY GROUPING COUNTRIES WITH COUNTRY_NAME
--- THEN INNER JOIN REGIONS AND COUNTRIES


SELECT R.REGION_NAME , COUNT(C.COUNTRY_NAME) AS "COUNTRY_COUNT"
FROM COUNTRIES C
INNER JOIN REGIONS R on C.REGION_ID = R.REGION_ID
GROUP BY R.REGION_NAME